### PR TITLE
Updating to be syntax compatible with Python 3

### PR DESCRIPTION
**Pull request by blarghmatey**

### CODE REVIEW

**Comment by pdpinch** [comment]
First time I've looked at this repo, and I have questions. 

But more to the task at hand -- after this change has been merged, this will only work with python3, right? I guess that's OK as long as we find a way to make it clear.

**Comment by blarghmatey** [comment]
Yes, this will only work on Python3 after merging. I can update the trove classifiers to make it clearer.

**Comment by pdpinch** [comment]
Is that going to be enough for _us_ to keep it straight? Since we are running it with Ironwood (python2) on xPRO and will run it with Juniper (python3) on Residential qa-next?

**Comment by blarghmatey** [comment]
For us, we have a tag of v0.1 that Ironwood is using and once this merges I'll be adding a v0.2 tag which we'll use for the Juniper deployment.

**Comment by markbreedlove** [comment]
Considering that there are tags to keep this from interfering with Ironwood deployments, is this OK to merge now? @pdpinch

**Pull request merged**
